DROP TABLE DEUDA_CORPORATIVO PURGE;
CREATE TABLE DEUDA_CORPORATIVO
(
  NRO_CUENTA               VARCHAR2(50),
  CUST_ACCOUNT_ID          VARCHAR2(50),
  CUSTOMER_ID              VARCHAR2(50),
  CUENTA_LARGA             VARCHAR2(50),
  RUC                      VARCHAR2(50),
  RAZON_SOCIAL             VARCHAR2(255),
  CICLO                    VARCHAR2(50),
  CICLO2                   VARCHAR2(50),
  PARTY_TYPE               VARCHAR2(50),
  GRUPO_FAC                VARCHAR2(50),
  ORIGEN                   VARCHAR2(50),
  CUSTOMER_TRX_ID          VARCHAR2(50),
  NRO_DOC                  VARCHAR2(50),
  EMISION                  DATE,
  VENCIMIENTO              DATE,
  MONEDA                   VARCHAR2(50),
  MONTO_FAC                NUMBER,
  MONTO_FAC_SOLES          NUMBER,
  CAMBIO                   NUMBER,
  SALDO                    NUMBER,
  SALDO_SOLES              NUMBER,
  RECLAMO                  NUMBER,
  RECLAMO_SOLES            NUMBER,
  OBS                      VARCHAR2(50),
  DIAS                     VARCHAR2(50),
  TRAMO_EMISION            VARCHAR2(50),
  TRAMO_VENCIMIENTO        VARCHAR2(50),
  DIA                      VARCHAR2(50),
  MES                      VARCHAR2(50),
  ANO                      VARCHAR2(50),
  ESTADO_DOCUMENTO         VARCHAR2(50),
  ESTADO_CONTABLE          VARCHAR2(50),
  ESTADO_CUENTA            VARCHAR2(50),
  TIPO_EMPRESA             VARCHAR2(50),
  COMMENTS                 VARCHAR2(255),
  START_DATE               VARCHAR2(50),
  PAYMENT_METHOD           VARCHAR2(50),
  CLASS                    VARCHAR2(50),
  NAME                     VARCHAR2(50),
  DESCRIPTION              VARCHAR2(50),
  TYPE                     VARCHAR2(50),
  CREATION_DATE            VARCHAR2(50),
  IDFAC                    VARCHAR2(50),
  INTERFACE_HEADER_CONTEXT VARCHAR2(50),
  GLOBAL_ATTRIBUTE13       VARCHAR2(50),
  IMEI                     VARCHAR2(50),
  FLAG_ONE                 VARCHAR2(50)
);
CREATE INDEX DEUDA_CORPORATIVO_IDX1 ON DEUDA_CORPORATIVO (CUST_ACCOUNT_ID);
CREATE INDEX DEUDA_CORPORATIVO_IDX2 ON DEUDA_CORPORATIVO (NRO_CUENTA);
CREATE INDEX DEUDA_CORPORATIVO_IDX3 ON DEUDA_CORPORATIVO (ORIGEN, TO_CHAR(EMISION,'YYYY'));