-- Language
SELECT
HCA.ACCOUNT_NUMBER AS NRO_CUENTA,
TO_CHAR(HCA.CUST_ACCOUNT_ID)CUST_ACCOUNT_ID,
HCA.ORIG_SYSTEM_REFERENCE CUSTOMER_ID,
HCA.ATTRIBUTE7 AS CUENTA_LARGA,
HZ.JGZZ_FISCAL_CODE RUC,
--CONCAT(CONCAT('"',REPLACE(REPLACE(REPLACE(HZ.PARTY_NAME,CHR(10),''),CHR(13),''),'"','')),'"') RAZON_SOCIAL,
CONVERT(HZ.PARTY_NAME, 'US7ASCII', 'WE8MSWIN1252')RAZON_SOCIAL,
HCA.ATTRIBUTE4 AS CICLO,
RCT.ATTRIBUTE11 CICLO2,
HZ.PARTY_TYPE,
RCT.ATTRIBUTE12 GRUPO_FAC,
HCA.ATTRIBUTE19 ORIGEN,
TO_CHAR(APS.CUSTOMER_TRX_ID)CUSTOMER_TRX_ID,
APS.TRX_NUMBER NRO_DOC,
TRUNC(APS.TRX_DATE) EMISION,
TRUNC(APS.DUE_DATE) VENCIMIENTO,
APS.INVOICE_CURRENCY_CODE MONEDA,
APS.AMOUNT_DUE_ORIGINAL MONTO_FAC,
DECODE(APS.INVOICE_CURRENCY_CODE,'PEN',NVL(APS.AMOUNT_DUE_ORIGINAL,0),'USD',NVL(APS.AMOUNT_DUE_ORIGINAL,0) * RCT.EXCHANGE_RATE) MONTO_FAC_SOLES,
NVL(RCT.EXCHANGE_RATE,1) CAMBIO,
APS.AMOUNT_DUE_REMAINING SALDO,
DECODE(APS.INVOICE_CURRENCY_CODE,'PEN',NVL(APS.AMOUNT_DUE_REMAINING,0),'USD',NVL(APS.AMOUNT_DUE_REMAINING,0) * RCT.EXCHANGE_RATE) SALDO_SOLES,
NVL(APS.AMOUNT_IN_DISPUTE,0)RECLAMO,
DECODE(APS.INVOICE_CURRENCY_CODE, 'PEN',NVL(APS.AMOUNT_IN_DISPUTE, 0),'USD',NVL(APS.AMOUNT_IN_DISPUTE, 0) * RCT.EXCHANGE_RATE)RECLAMO_SOLES,
(CASE WHEN APS.AMOUNT_DUE_REMAINING>0 THEN 'DEUDA' ELSE 'SALDO A FAVOR'END)OBS,
TO_DATE(SYSDATE,'DD/MM/YY')-TO_DATE(APS.DUE_DATE,'DD/MM/YY') AS DIAS,
(CASE WHEN TRUNC(SYSDATE)- TRUNC(aps.trx_date) <1   THEN  '1. Por vencer'
     WHEN TRUNC(SYSDATE)- TRUNC(aps.trx_date) <31  THEN  '2. 1 a 30'
     WHEN TRUNC(SYSDATE)- TRUNC(aps.trx_date) <61  THEN  '3. 31 a 60'
     WHEN TRUNC(SYSDATE)- TRUNC(aps.trx_date) <91  THEN  '4. 61 a 90'
     WHEN TRUNC(SYSDATE)- TRUNC(aps.trx_date) <121 THEN  '5. 91 a 120'
     WHEN TRUNC(SYSDATE)- TRUNC(aps.trx_date) <151 THEN  '6. 121 a 150'
     WHEN TRUNC(SYSDATE)- TRUNC(aps.trx_date) <211 THEN  '7. 151 a 210'
     WHEN TRUNC(SYSDATE)- TRUNC(aps.trx_date) <365 THEN  '8. 211 a 364'
     WHEN TRUNC(SYSDATE)- TRUNC(aps.trx_date) >=365 THEN '9. 365 a mas' END) TRAMO_EMISION,
(CASE WHEN TRUNC(SYSDATE)- TRUNC(aps.due_date) <1   THEN  '1. Por vencer'
     WHEN TRUNC(SYSDATE)- TRUNC(aps.due_date) <31  THEN  '2. 1 a 30'
     WHEN TRUNC(SYSDATE)- TRUNC(aps.due_date) <61  THEN  '3. 31 a 60'
     WHEN TRUNC(SYSDATE)- TRUNC(aps.due_date) <91  THEN  '4. 61 a 90'
     WHEN TRUNC(SYSDATE)- TRUNC(aps.due_date) <121 THEN  '5. 91 a 120'
     WHEN TRUNC(SYSDATE)- TRUNC(aps.due_date) <151 THEN  '6. 121 a 150'
     WHEN TRUNC(SYSDATE)- TRUNC(aps.due_date) <211 THEN  '7. 151 a 210'
     WHEN TRUNC(SYSDATE)- TRUNC(aps.due_date) <365 THEN  '8. 211 a 364'
     WHEN TRUNC(SYSDATE)- TRUNC(aps.due_date) >=365 THEN '9. 365 a mas' END) TRAMO_VENCIMIENTO,
TO_CHAR(aps.due_date, 'DD') DIA,
TO_CHAR(aps.due_date, 'MM') MES,
TO_CHAR(aps.due_date, 'YYYY') ANO,
RCT.ATTRIBUTE6 ESTADO_DOCUMENTO,
RCT.ATTRIBUTE1 ESTADO_CONTABLE,---CASTIGADO PARA VALIDARLO
HCA.ATTRIBUTE1 ESTADO_CUENTA,
DECODE(NVL(HZ.ATTRIBUTE7, '00'),
'00','MASIVO',
'01','CARRIER',
'02','CLARO',
'03','CORPORACIONES',
'04','CORPORACIONES VIP',
'05','EMPRESAS',
'06','EMPRESAS VIP',
'07','ESPECIALES',
'08','GOBIERNO',
'09','LICITACION','PYMES') AS TIPO_EMPRESA,
RCT.COMMENTS,
TO_CHAR(HCA.ATTRIBUTE2) START_DATE,
HCA.ATTRIBUTE5 PAYMENT_METHOD,
APS.CLASS,--CLASEDEDOCUMENTO,
RCTT.NAME,--TIPODEDOCUMENTO,
RCTT.DESCRIPTION,--DESCRIPTIPODOC,
RCTT.TYPE,
TO_CHAR(APS.CREATION_DATE,'DD-MON-YY')CREATION_DATE,
TO_CHAR(INTERFACE_HEADER_ATTRIBUTE1) IDFAC,
TO_CHAR(RCT.INTERFACE_HEADER_CONTEXT)INTERFACE_HEADER_CONTEXT,
TO_CHAR(RCT.GLOBAL_ATTRIBUTE13)GLOBAL_ATTRIBUTE13, ----RECIBO AL QUE VIAJA LA CUOTA
TO_CHAR(RCT.GLOBAL_ATTRIBUTE6) IMEI, --IMEI
TO_CHAR(HCA.GLOBAL_ATTRIBUTE20) FLAG_ONE
FROM AR.HZ_CUST_ACCOUNTS HCA,
    AR.RA_CUSTOMER_TRX_ALL RCT,
    AR.AR_PAYMENT_SCHEDULES_ALL APS,
    AR.HZ_PARTIES HZ,
    AR.RA_CUST_TRX_TYPES_ALL RCTT
WHERE HCA.CUST_ACCOUNT_ID = RCT.BILL_TO_CUSTOMER_ID
AND RCT.CUSTOMER_TRX_ID = APS.CUSTOMER_TRX_ID
AND RCTT.CUST_TRX_TYPE_ID = RCT.CUST_TRX_TYPE_ID
AND HCA.PARTY_ID = HZ.PARTY_ID
AND APS.AMOUNT_DUE_REMAINING <>0
AND HCA.ATTRIBUTE19 IN ('BSCS','SGA')
--AND RCT.ATTRIBUTE1 <> 'ANULADO'
AND LENGTH(HZ.JGZZ_FISCAL_CODE)='11'
--and hz.jgzz_fiscal_code IN ('20605458123','20523917332','20536600290','20546294278')


